[package]
name = "steward"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 2

[workspace]
members = ["crates/*"]

[workspace.dependencies]
macroquad = { version = "0.4.4" }
num_enum = { version = "*" }
pathfinding = { version = "*" }
strum = { version = "*", features = ["derive"] }
rayon = { version = "*" }

gui = { path = "crates/gui" }
util = { path = "crates/util" }

[dependencies]
macroquad = { workspace = true }
num_enum = { workspace = true }
pathfinding = { workspace = true }
strum = { workspace = true }
rayon = { workspace = true }

gui = { workspace = true }
util = { workspace = true }
